services:
  app:
    container_name: ibank-app
    build:
      context: .
      target: ${DOCKER_TARGET:-development}
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/app
      - /app/node_modules
      # - /app/dist
    networks:
      - ibank
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: ibank-db
    image: postgres:17-alpine
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
     - '5432:5432'
    volumes:
    - postgres_data:/var/lib/postgresql/data
    networks:
      - ibank
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  ibank:
    driver: bridge

volumes:
 postgres_data: